// <auto-generated />
using System;
using Guia.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Guia.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506205311_InicialMySQL")]
    partial class InicialMySQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Guia.API.Models.ArbolVida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Binah_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Binah_Nombre");

                    b.Property<int>("Binah_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Binah_Valor");

                    b.Property<string>("Chesed_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Chesed_Nombre");

                    b.Property<int>("Chesed_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Chesed_Valor");

                    b.Property<string>("Chokmah_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Chokmah_Nombre");

                    b.Property<int>("Chokmah_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Chokmah_Valor");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Gevurah_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Gevurah_Nombre");

                    b.Property<int>("Gevurah_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Gevurah_Valor");

                    b.Property<string>("Hod_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Hod_Nombre");

                    b.Property<int>("Hod_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Hod_Valor");

                    b.Property<string>("Kether_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Kether_Nombre");

                    b.Property<int>("Kether_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Kether_Valor");

                    b.Property<string>("Malchut_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Malchut_Nombre");

                    b.Property<int>("Malchut_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Malchut_Valor");

                    b.Property<string>("Netzach_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Netzach_Nombre");

                    b.Property<int>("Netzach_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Netzach_Valor");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_1_2")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_1_3")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_1_6")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_2_3")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_2_4")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_2_6")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_3_5")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_3_6")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_4_5")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_4_6")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_4_7")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_5_6")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_5_8")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_6_7")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_6_8")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_6_9")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_7_10")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_7_8")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_7_9")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_8_10")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_8_9")
                        .HasColumnType("int");

                    b.Property<int>("Sendero_9_10")
                        .HasColumnType("int");

                    b.Property<string>("Tiferet_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Tiferet_Nombre");

                    b.Property<int>("Tiferet_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Tiferet_Valor");

                    b.Property<string>("Yesod_Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Yesod_Nombre");

                    b.Property<int>("Yesod_Valor")
                        .HasColumnType("int")
                        .HasColumnName("Yesod_Valor");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("ArbolesVida");
                });

            modelBuilder.Entity("Guia.API.Models.Arcano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ElementoOPlaneta")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("LetraHebrea")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Mensaje")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("SignificadoEsoterico")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Arcanos");
                });

            modelBuilder.Entity("Guia.API.Models.Arquetipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ElementoOPlaneta")
                        .HasColumnType("longtext");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("LetraHebrea")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Mensaje")
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("SignificadoEsoterico")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Arquetipos");
                });

            modelBuilder.Entity("Guia.API.Models.Bitacora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoReto")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<int?>("RetoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ValorSincronico")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.HasIndex("RetoId");

                    b.ToTable("Bitacoras");
                });

            modelBuilder.Entity("Guia.API.Models.ElementoAstro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Esencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ElementosAstro");
                });

            modelBuilder.Entity("Guia.API.Models.FaseLunar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Recomendacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SignificadoEspiritual")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FasesLunares");
                });

            modelBuilder.Entity("Guia.API.Models.FraseGratitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FrasesGratitud");
                });

            modelBuilder.Entity("Guia.API.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Guia.API.Models.PersonaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FaseLunar")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("MensajeGratitud")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NotasAstrologicas")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.Property<string>("SignoZodiaco")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("VibracionDia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("PersonasDetalles");
                });

            modelBuilder.Entity("Guia.API.Models.PersonaNumerologia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LeccionVida")
                        .HasColumnType("int");

                    b.Property<int>("MisionVida")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroAlma")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDestino")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPersonalidad")
                        .HasColumnType("int");

                    b.Property<int>("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("PersonasNumerologia");
                });

            modelBuilder.Entity("Guia.API.Models.RetoSemanal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dificultad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsGlobal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Instrucciones")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("NumeroAsociado")
                        .HasColumnType("int");

                    b.Property<int>("TemaId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("RetosSemanales");
                });

            modelBuilder.Entity("Guia.API.Models.Significado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amuleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Apodo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mantra")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MensajeMagico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mision")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TemaId")
                        .HasColumnType("int");

                    b.Property<int>("ValorNumero")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemaId");

                    b.ToTable("Significados");
                });

            modelBuilder.Entity("Guia.API.Models.SignoZodiacal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionLarga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Elemento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Icono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PalabrasClave")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("SignosZodiacales");
                });

            modelBuilder.Entity("Guia.API.Models.Tema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionGeneral")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EsGratis")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Temas");
                });

            modelBuilder.Entity("Guia.API.Models.ArbolVida", b =>
                {
                    b.HasOne("Guia.API.Models.Persona", "Persona")
                        .WithOne("ArbolVida")
                        .HasForeignKey("Guia.API.Models.ArbolVida", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Guia.API.Models.Bitacora", b =>
                {
                    b.HasOne("Guia.API.Models.Persona", "Persona")
                        .WithMany()
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Guia.API.Models.RetoSemanal", "Reto")
                        .WithMany()
                        .HasForeignKey("RetoId");

                    b.Navigation("Persona");

                    b.Navigation("Reto");
                });

            modelBuilder.Entity("Guia.API.Models.PersonaDetalle", b =>
                {
                    b.HasOne("Guia.API.Models.Persona", "Persona")
                        .WithOne("Detalle")
                        .HasForeignKey("Guia.API.Models.PersonaDetalle", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Guia.API.Models.PersonaNumerologia", b =>
                {
                    b.HasOne("Guia.API.Models.Persona", "Persona")
                        .WithOne("Numerologia")
                        .HasForeignKey("Guia.API.Models.PersonaNumerologia", "PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("Guia.API.Models.RetoSemanal", b =>
                {
                    b.HasOne("Guia.API.Models.Tema", "Tema")
                        .WithMany()
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Guia.API.Models.Significado", b =>
                {
                    b.HasOne("Guia.API.Models.Tema", "Tema")
                        .WithMany("Significados")
                        .HasForeignKey("TemaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tema");
                });

            modelBuilder.Entity("Guia.API.Models.Persona", b =>
                {
                    b.Navigation("ArbolVida");

                    b.Navigation("Detalle");

                    b.Navigation("Numerologia");
                });

            modelBuilder.Entity("Guia.API.Models.Tema", b =>
                {
                    b.Navigation("Significados");
                });
#pragma warning restore 612, 618
        }
    }
}
